GET http://localhost:3000/users

#####

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Hizkia",
    "email": "hizkia@gmail.com",
    "password": "Hizkia3006"
}

#####

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "hizkia@gmail.com",
    "password": "Hizkia3006"
}